import type { Hotel, Traveler } from "./types";

export const SEED_NIGHTS = 4;
export const SEED_DESTINATION = "Lisbon, Portugal";

export const seedTravelers: Traveler[] = [
  {
    id: "t-maya",
    name: "Maya",
    avatarHue: 160,
    budgetPerNight: 180,
    constraints: [
      { id: "c-maya-1", label: "Step-free access", category: "accessibility", priority: "must", weight: 10, locked: true },
      { id: "c-maya-2", label: "Roll-in shower", category: "accessibility", priority: "prefer", weight: 6, locked: false },
      { id: "c-maya-3", label: "City center", category: "location", priority: "prefer", weight: 5, locked: false },
    ],
  },
  {
    id: "t-diego",
    name: "Diego",
    avatarHue: 30,
    budgetPerNight: 120,
    constraints: [
      { id: "c-diego-1", label: "Under 130/night", category: "budget", priority: "must", weight: 9, locked: true },
      { id: "c-diego-2", label: "Free cancellation", category: "cancellation", priority: "prefer", weight: 7, locked: false },
      { id: "c-diego-3", label: "Breakfast included", category: "amenity", priority: "flexible", weight: 3, locked: false },
    ],
  },
  {
    id: "t-sana",
    name: "Sana",
    avatarHue: 280,
    budgetPerNight: 220,
    constraints: [
      { id: "c-sana-1", label: "Kids stay free / family rooms", category: "family", priority: "must", weight: 10, locked: true },
      { id: "c-sana-2", label: "Pool", category: "amenity", priority: "prefer", weight: 6, locked: false },
      { id: "c-sana-3", label: "Near beach", category: "location", priority: "prefer", weight: 5, locked: false },
    ],
  },
  {
    id: "t-leo",
    name: "Leo",
    avatarHue: 200,
    budgetPerNight: 260,
    constraints: [
      { id: "c-leo-1", label: "Review score 8.5+", category: "rating", priority: "prefer", weight: 7, locked: false },
      { id: "c-leo-2", label: "No all-inclusive resorts", category: "amenity", priority: "exclude", weight: 8, locked: false },
      { id: "c-leo-3", label: "Gym", category: "amenity", priority: "flexible", weight: 3, locked: false },
    ],
  },
];

export const seedHotels: Hotel[] = [
  {
    id: "h-aurora",
    name: "Aurora Riverside",
    location: "City Center",
    nightlyPrice: 165,
    totalPrice: 660,
    currency: "EUR",
    rating: 4,
    reviewScore: 8.9,
    cancellation: "free",
    amenities: ["step-free access", "roll-in shower", "breakfast included", "gym"],
    imageGradient: "linear-gradient(135deg,#0f6b5c,#164e63)",
    distanceKm: 0.8,
    roomsAvailable: 5,
  },
  {
    id: "h-solmar",
    name: "Solmar Beach Club",
    location: "Costa da Caparica",
    nightlyPrice: 190,
    totalPrice: 760,
    currency: "EUR",
    rating: 4,
    reviewScore: 8.2,
    cancellation: "partial",
    amenities: ["pool", "family rooms", "kids stay free", "beachfront"],
    imageGradient: "linear-gradient(135deg,#0284c7,#f59e0b)",
    distanceKm: 0.1,
    roomsAvailable: 8,
  },
  {
    id: "h-pensao",
    name: "Pensão Lumen",
    location: "Baixa",
    nightlyPrice: 95,
    totalPrice: 380,
    currency: "EUR",
    rating: 3,
    reviewScore: 7.6,
    cancellation: "free",
    amenities: [
      "breakfast included",
      "city center",
      "step-free access",
      "family rooms",
      "kids stay free",
    ],
    imageGradient: "linear-gradient(135deg,#78350f,#b45309)",
    distanceKm: 0.3,
    roomsAvailable: 3,
  },
  {
    id: "h-meridiano",
    name: "Meridiano Grand",
    location: "Avenida da Liberdade",
    nightlyPrice: 240,
    totalPrice: 960,
    currency: "EUR",
    rating: 5,
    reviewScore: 9.3,
    cancellation: "free",
    amenities: ["step-free access", "roll-in shower", "gym", "pool", "family rooms"],
    imageGradient: "linear-gradient(135deg,#1e1b4b,#7c3aed)",
    distanceKm: 1.4,
    roomsAvailable: 6,
  },
  {
    id: "h-casa-verde",
    name: "Casa Verde Garden Hotel",
    location: "Alfama",
    nightlyPrice: 128,
    totalPrice: 512,
    currency: "EUR",
    rating: 3,
    reviewScore: 8.6,
    cancellation: "partial",
    amenities: ["breakfast included", "garden", "city center"],
    imageGradient: "linear-gradient(135deg,#166534,#65a30d)",
    distanceKm: 0.6,
    roomsAvailable: 4,
  },
  {
    id: "h-oceana",
    name: "Oceana Resort & Spa",
    location: "Cascais",
    nightlyPrice: 210,
    totalPrice: 840,
    currency: "EUR",
    rating: 4,
    reviewScore: 8.8,
    cancellation: "non-refundable",
    amenities: ["pool", "spa", "family rooms", "all-inclusive", "beachfront", "step-free access"],
    imageGradient: "linear-gradient(135deg,#0e7490,#f97316)",
    distanceKm: 0.2,
    roomsAvailable: 10,
  },
];
